// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.7
// source: tools.proto

package msg

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ToolsManagerClient is the client API for ToolsManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ToolsManagerClient interface {
	// Sends a greeting
	Register(ctx context.Context, in *ReqRegister, opts ...grpc.CallOption) (*ReplyRegister, error)
	ReportTaskCurrentState(ctx context.Context, in *ReportTaskState, opts ...grpc.CallOption) (*ReplyReport, error)
}

type toolsManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewToolsManagerClient(cc grpc.ClientConnInterface) ToolsManagerClient {
	return &toolsManagerClient{cc}
}

func (c *toolsManagerClient) Register(ctx context.Context, in *ReqRegister, opts ...grpc.CallOption) (*ReplyRegister, error) {
	out := new(ReplyRegister)
	err := c.cc.Invoke(ctx, "/msg.ToolsManager/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolsManagerClient) ReportTaskCurrentState(ctx context.Context, in *ReportTaskState, opts ...grpc.CallOption) (*ReplyReport, error) {
	out := new(ReplyReport)
	err := c.cc.Invoke(ctx, "/msg.ToolsManager/ReportTaskCurrentState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ToolsManagerServer is the server API for ToolsManager service.
// All implementations must embed UnimplementedToolsManagerServer
// for forward compatibility
type ToolsManagerServer interface {
	// Sends a greeting
	Register(context.Context, *ReqRegister) (*ReplyRegister, error)
	ReportTaskCurrentState(context.Context, *ReportTaskState) (*ReplyReport, error)
	mustEmbedUnimplementedToolsManagerServer()
}

// UnimplementedToolsManagerServer must be embedded to have forward compatible implementations.
type UnimplementedToolsManagerServer struct {
}

func (UnimplementedToolsManagerServer) Register(context.Context, *ReqRegister) (*ReplyRegister, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedToolsManagerServer) ReportTaskCurrentState(context.Context, *ReportTaskState) (*ReplyReport, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportTaskCurrentState not implemented")
}
func (UnimplementedToolsManagerServer) mustEmbedUnimplementedToolsManagerServer() {}

// UnsafeToolsManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ToolsManagerServer will
// result in compilation errors.
type UnsafeToolsManagerServer interface {
	mustEmbedUnimplementedToolsManagerServer()
}

func RegisterToolsManagerServer(s grpc.ServiceRegistrar, srv ToolsManagerServer) {
	s.RegisterService(&ToolsManager_ServiceDesc, srv)
}

func _ToolsManager_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqRegister)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolsManagerServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/msg.ToolsManager/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolsManagerServer).Register(ctx, req.(*ReqRegister))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolsManager_ReportTaskCurrentState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportTaskState)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolsManagerServer).ReportTaskCurrentState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/msg.ToolsManager/ReportTaskCurrentState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolsManagerServer).ReportTaskCurrentState(ctx, req.(*ReportTaskState))
	}
	return interceptor(ctx, in, info, handler)
}

// ToolsManager_ServiceDesc is the grpc.ServiceDesc for ToolsManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ToolsManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "msg.ToolsManager",
	HandlerType: (*ToolsManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _ToolsManager_Register_Handler,
		},
		{
			MethodName: "ReportTaskCurrentState",
			Handler:    _ToolsManager_ReportTaskCurrentState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tools.proto",
}
